Make all names Rubik medium 14px, right side wight 720px instead of 30%
BinaryStudioAcademy/bsa-2021-slidez pull request #102
Opened 2021-08-17 18:36 UTC by NDMyroshnychenko

- Make all names: "No account? Sign Up", "Forgot Password", Email, Password Rubik medium 14px

- Fix Ratio for left/right sides. Please check also smaller resolutions - like 1366x768. Rigth side should be always 720px instead of 30%.

2021-08-17 20:32 UTC, Anatolii-Ivanov requested changes

2021-08-17 20:32 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/common/components/forms/sign-form.scss
> +    font-family: "Rubik", sans-serif;
Set font-family globally (for div or input component)

2021-08-17 20:32 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/common/components/forms/sign-form.scss
> +    font-family: "Rubik", sans-serif;
Everywhere

2021-08-17 20:32 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/common/components/forms/sign-form.scss
> +    font-family: "Rubik", sans-serif;
Check in F12 elements, most of this elements should already has correct font-family

2021-08-19 12:48 UTC, Anatolii-Ivanov approved these changes

2021-08-19 15:51 UTC, AnnaPrusakova approved these changes

2021-08-19 19:29 UTC, merged