Added Q&A component view (with some inaccuracies, view todos)
BinaryStudioAcademy/bsa-2021-slidez pull request #112
Opened 2021-08-19 07:36 UTC by VladislavArzamastsev

2021-08-19 12:48 UTC, Anatolii-Ivanov approved these changes

2021-08-22 21:13 UTC, Anatolii-Ivanov commented
Is it relevant after your new PR?

2021-08-22 21:19 UTC, VladislavArzamastsev commented
Not really, new PR is better. I should shut down this one

2021-08-23 06:26 UTC, klesogor requested changes

2021-08-23 06:26 UTC, klesogor commented on slidez-core/src/main/resources/db/migration/V1.1__case_insensitive_email.sql
> +create collation IF NOT EXISTS case_insensitive
Please, don't change existing migrations. Everyone who already applied it will see hash mismatch message

2021-08-23 06:26 UTC, klesogor commented on slidez-core/src/main/resources/new_database/script.sql
> +CREATE TABLE IF NOT EXISTS "user" (
again, generating DB from zero. We need to update existing migrations, not re-write them from scratch

2021-08-23 06:49 UTC, closed without merging