#58 setup google slides addon project
BinaryStudioAcademy/bsa-2021-slidez pull request #12
Opened 2021-07-30 09:59 UTC by Max44444

2021-07-30 17:24 UTC, Anatolii-Ivanov requested changes
Add package-lock.json to gitignore

2021-07-30 17:24 UTC, Anatolii-Ivanov commented on slidez-fe-addon/README.md
> +<p align="center">
Are you sure this file is needed?

2021-07-30 17:24 UTC, Anatolii-Ivanov commented on slidez-fe-addon/src/client/README.md
> +# Client (our React code)
Check if all Readme is needed

2021-07-30 17:24 UTC, Anatolii-Ivanov commented on slidez-fe-addon/src/client/sidebar-demo/index.html
> +<!DOCTYPE html>
It's better to give correct names for files, as it seems to be  just a sidebar later, but it FYI

2021-08-03 05:24 UTC, klesogor approved these changes

2021-08-03 07:23 UTC, NDMyroshnychenko approved these changes

2021-08-03 07:31 UTC, Max44444 reviewed
.

2021-08-03 07:36 UTC, Anatolii-Ivanov approved these changes

2021-08-03 07:37 UTC, merged