add notification for incorrect data on login
BinaryStudioAcademy/bsa-2021-slidez pull request #124
Opened 2021-08-20 06:56 UTC by AnnaPrusakova

2021-08-20 14:58 UTC, VolodymyrYavorskyi approved these changes

2021-08-22 21:09 UTC, Anatolii-Ivanov requested changes

2021-08-22 21:09 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/common/components/forms/LoginForm.tsx
> +    const GoogleLoginFailed = () => {
GogleLoginFailed -> googleLoginFailed

2021-08-22 21:09 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/common/components/forms/LoginForm.tsx
> +                            {() => loginFailed(errors.email)}
Check it after login request, here it will be shown on any page update if login is failed

2021-08-22 21:09 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/common/components/forms/RegistrationForm.tsx
> +                                {registrationFailed}
The same

2021-08-25 19:17 UTC, Anatolii-Ivanov commented
Fix linter

2021-08-25 19:17 UTC, Anatolii-Ivanov approved these changes

2021-08-26 06:52 UTC, VolodymyrYavorskyi approved these changes

2021-08-26 08:13 UTC, merged