add reducer for poll
BinaryStudioAcademy/bsa-2021-slidez pull request #125
Opened 2021-08-20 06:57 UTC by AnnaPrusakova

2021-08-20 15:00 UTC, VolodymyrYavorskyi approved these changes

2021-08-22 21:11 UTC, Anatolii-Ivanov requested changes

2021-08-22 21:11 UTC, Anatolii-Ivanov commented on slidez-extension/src/components/poll/Poll.tsx
> +                        {animatePercent}
Please, execute functions only on some events, not like a code part (You can make so only if it returns some data)

2021-09-01 11:39 UTC, Anatolii-Ivanov approved these changes

2021-09-03 07:20 UTC, closed without merging