fix grid size
BinaryStudioAcademy/bsa-2021-slidez pull request #127
Opened 2021-08-20 09:30 UTC by AnnaPrusakova

2021-08-20 10:46 UTC, Anatolii-Ivanov requested changes

2021-08-20 10:46 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/dashboard/dashboard.scss
> +		grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
Add gap please
https://developer.mozilla.org/en-US/docs/Web/CSS/gap

2021-08-20 15:01 UTC, VolodymyrYavorskyi approved these changes

2021-08-22 21:11 UTC, Anatolii-Ivanov approved these changes

2021-08-23 07:23 UTC, merged