Feature/178 main addon page
BinaryStudioAcademy/bsa-2021-slidez pull request #139
Opened 2021-08-23 16:59 UTC by alex-tiutiunnyk

2021-08-23 17:27 UTC, Anatolii-Ivanov requested changes

2021-08-23 17:27 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/containers/poll-editor/PollEditor.tsx
> +    const handleSubmit = (values: any) => {
Don't use any

2021-08-23 17:27 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/containers/poll-editor/PollEditor.tsx
> +const PollEditor = () => {
Add type here, why you delete it?

2021-08-24 07:07 UTC, klesogor approved these changes

2021-08-24 07:07 UTC, klesogor commented on slidez-fe-core/src/App.tsx
>  log()
Remove it please, it's not necessary anymore

2021-08-24 12:59 UTC, Anatolii-Ivanov approved these changes

2021-08-25 07:55 UTC, merged