Feature/115 delete account
BinaryStudioAcademy/bsa-2021-slidez pull request #148
Opened 2021-08-25 16:46 UTC by AnnaPrusakova

2021-08-25 19:23 UTC, Anatolii-Ivanov requested changes

2021-08-25 19:23 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/containers/delete-account/DeleteAccount.tsx
> +                        handleDeleteAccount({ id: userId, email: userEmail })
Get userId from token! This way user can delete any other user using his id

2021-08-25 19:23 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/containers/delete-account/DeleteAccount.tsx
> +    children?: never[]
Why you added them?

2021-08-25 19:23 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/containers/delete-account/DeleteAccount.tsx
> +    })
Please, don't get token here... Just send request to delete user. Token should be set using http-helper by default as a header

2021-09-01 09:02 UTC, VolodymyrYavorskyi approved these changes

2021-09-01 11:39 UTC, Anatolii-Ivanov approved these changes

2021-09-01 13:03 UTC, merged