Feature/177 participant view
BinaryStudioAcademy/bsa-2021-slidez pull request #151
Opened 2021-08-26 08:48 UTC by alex-tiutiunnyk

2021-08-26 09:00 UTC, Anatolii-Ivanov requested changes

2021-08-26 09:00 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/event/ParticipantView.tsx
> +                    </RadioGroup>
Build it from some data (create mocked array of answers on the top of the file)

2021-08-26 11:33 UTC, Anatolii-Ivanov approved these changes

2021-08-27 08:44 UTC, VL4DYSL4V approved these changes

2021-08-27 08:50 UTC, merged