Feature/191 implement qa form
BinaryStudioAcademy/bsa-2021-slidez pull request #166
Opened 2021-08-31 09:26 UTC by Kosichenko

2021-08-31 10:45 UTC, Anatolii-Ivanov requested changes

2021-08-31 10:45 UTC, Anatolii-Ivanov commented on slidez-fe-core/package.json
> +    "singleQuote": true
Can you remove it?

2021-08-31 10:45 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/containers/sideBar/SideBar.tsx
> +                <Qa show={showQAModal} handleClose={() => handleQAClose()}></Qa>
I don't think that we need this button here

2021-08-31 10:45 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/participant-page/Header.tsx
>              <div className='event-name'>{eventName}</div>
And here

2021-08-31 10:45 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/participant-page/ParticipantPage.tsx
> +            <Qa show={showQAModal} handleClose={() => handleQAClose()}></Qa>
Alexandra added places to this button on poll component and empty page, please, add button there

2021-08-31 10:45 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/qa/Qa.tsx
> +            UUID: now,
UUID should not be set on frontend, don't define it (nullable)

2021-08-31 10:59 UTC, Kosichenko commented on slidez-fe-core/package.json
> +    "singleQuote": true
Fixed

2021-09-01 09:58 UTC, Kosichenko commented on slidez-fe-core/src/containers/sideBar/SideBar.tsx
> +                <Qa show={showQAModal} handleClose={() => handleQAClose()}></Qa>
Fixed

2021-09-01 09:58 UTC, Kosichenko commented on slidez-fe-core/src/pages/participant-page/ParticipantPage.tsx
> +            <Qa show={showQAModal} handleClose={() => handleQAClose()}></Qa>
It's cool! I'll will done it.

2021-09-01 09:58 UTC, Kosichenko commented on slidez-fe-core/src/pages/qa/Qa.tsx
> +            UUID: now,
fixed

2021-09-01 09:58 UTC, Kosichenko commented on slidez-fe-core/src/pages/qa/Qa.tsx
> +            UUID: now,
But than like button will work incorrect cause like depends on UUID.

2021-09-01 11:38 UTC, Anatolii-Ivanov approved these changes

2021-09-01 12:02 UTC, alex-tiutiunnyk approved these changes

2021-09-01 13:47 UTC, merged