Add base database structure
BinaryStudioAcademy/bsa-2021-slidez pull request #2
Opened 2021-07-28 15:43 UTC by AnnaPrusakova

Add migration and initial model, repository, and dto for user.

2021-07-28 17:45 UTC, Anatolii-Ivanov approved these changes

2021-07-29 06:33 UTC, klesogor requested changes

2021-07-29 06:33 UTC, klesogor commented on slidez-core/src/main/resources/db/migration/V1__create_user_table.sql
> +    email varchar(255) unique,
email index should be case insensitive

2021-07-29 06:55 UTC, klesogor approved these changes

2021-07-29 06:55 UTC, merged