Add possibility to clear the input
BinaryStudioAcademy/bsa-2021-slidez pull request #213
Opened 2021-09-06 07:22 UTC by alex-tiutiunnyk

2021-09-06 07:49 UTC, Anatolii-Ivanov requested changes

2021-09-06 07:49 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/containers/poll-editor/PollEditor.tsx
> +        setFieldValue: any
Can you add types, please?)

2021-09-06 07:49 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/containers/poll-editor/PollEditor.tsx
> +            console.log(index)
No console.logs

2021-09-06 18:51 UTC, Anatolii-Ivanov approved these changes

2021-09-07 17:47 UTC, VladislavArzamastsev approved these changes

2021-09-07 17:47 UTC, merged