Feature/61 link generation service
BinaryStudioAcademy/bsa-2021-slidez pull request #36
Opened 2021-08-03 10:32 UTC by NDMyroshnychenko

Link is a shorthand, that will be used to generate an access QR code.
Service should support the following operations:
1) [On startup, on corn job] Generate extra links, if there are less than 100 available
2) Lease a link. In this case, the caller provides info on how long it would like to lease a link. The maximum lease duration is 180 days
3) [On cron job] Clean up expired leases, freeing the links to be used again

2021-08-03 12:54 UTC, VladislavArzamastsev approved these changes

2021-08-03 18:50 UTC, Anatolii-Ivanov requested changes

2021-08-03 18:50 UTC, Anatolii-Ivanov commented on slidez-core/src/main/java/com/binarystudio/academy/slidez/link/LinkGenerationService.java
> +		}
if (countAvailableLinks **>=** this.MAX_COUNT_AVAILABLE_LINKS) {
return;
}

int countLinkForGenerate = this.MAX_COUNT_AVAILABLE_LINKS - countAvailableLinks;
			String lastLink = getLastLink();
			for (int i = 0; i < countLinkForGenerate; i++) {
				String newLink = generateLink(lastLink);
				this.linkRepository.save(new Link(UUID.randomUUID(), null, newLink, null));
				lastLink = newLink;
			}

2021-08-03 18:50 UTC, Anatolii-Ivanov commented on slidez-core/src/main/java/com/binarystudio/academy/slidez/link/LinkGenerationService.java
> +					isChange = true;
You don't need to set isChange = true here

2021-08-03 18:50 UTC, Anatolii-Ivanov commented on slidez-core/src/main/java/com/binarystudio/academy/slidez/link/LinkGenerationService.java
> +					isChange = true;
and here

2021-08-04 06:28 UTC, klesogor requested changes

2021-08-04 06:28 UTC, klesogor commented on slidez-core/src/main/java/com/binarystudio/academy/slidez/link/LinkGenerationService.java
> +			this.linkRepository.save(new Link(UUID.randomUUID(), null, newLink, null));
A batch operation would be preferable since 100 requests to DB generates quite some load

2021-08-04 06:28 UTC, klesogor commented on slidez-core/src/main/java/com/binarystudio/academy/slidez/link/LinkRepository.java
> +	@Query(value = "select * from Link where expiration_date <= cast((now()) as date)", nativeQuery = true)
`now()` is a bad practice, it makes debugging, testing, and reusing hard. Please, make it a parameter

2021-08-04 06:28 UTC, klesogor commented on slidez-core/src/main/java/com/binarystudio/academy/slidez/link/model/Link.java
> +	private Long sessionId;
This will be a UUID

2021-08-04 06:28 UTC, klesogor commented on slidez-core/src/main/java/com/binarystudio/academy/slidez/link/model/Link.java
> +	private UUID linkId;
Initially, this field should've been a Long, but since we're using links as an order(which is plausible), this is ok

2021-08-04 06:28 UTC, klesogor commented on slidez-core/src/main/java/com/binarystudio/academy/slidez/link/LinkGenerationService.java
> +		for (int i = newLink.length - 1; i >= 0; i--) {
It seems to me that this implementation is a bit off

2021-08-04 06:49 UTC, klesogor commented on slidez-core/src/main/java/com/binarystudio/academy/slidez/link/LinkGenerationService.java
> +		return this.linkRepository.getLastLink().orElse("AAAAA0");
Use lower case

2021-08-06 08:30 UTC, closed without merging