Google oauth added
BinaryStudioAcademy/bsa-2021-slidez pull request #40
Opened 2021-08-04 12:19 UTC by VladislavArzamastsev

2021-08-04 13:31 UTC, VolodymyrYavorskyi approved these changes

2021-08-04 13:31 UTC, VolodymyrYavorskyi commented on slidez-core/build.gradle
> +	implementation group: 'org.springdoc', name: 'springdoc-openapi-security', version: '1.5.9'
duplicate dependencies

2021-08-05 06:14 UTC, VolodymyrYavorskyi approved these changes

2021-08-05 07:14 UTC, VladislavArzamastsev commented
In staging properties you have to add "oauth2.redirect-uri" and "oauth2.client-id"

2021-08-06 06:20 UTC, Anatolii-Ivanov requested changes

2021-08-06 06:20 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/services/auth/auth-service.ts
> +    'http://localhost:5000/auth/register/google'
Don't use http://localhost:5000 in code, on staging this route will be different and it won't work

2021-08-06 06:20 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/services/auth/google-oauth.enum.ts
> +}
Move it to env variables(Id + URI)
And it's not enum

2021-08-06 07:36 UTC, Anatolii-Ivanov approved these changes

2021-08-06 07:41 UTC, merged