Feature/79 client side Poll and PollInput components
BinaryStudioAcademy/bsa-2021-slidez pull request #55
Opened 2021-08-06 12:24 UTC by VolodymyrYavorskyi

Temporarily added paths '/poll' and '/poll-input' to examine components

2021-08-09 12:02 UTC, Anatolii-Ivanov approved these changes

2021-08-10 06:26 UTC, klesogor commented on slidez-fe-core/src/components/poll/Poll.tsx
> +    for (let k in answers) {
Could be re-written in a declarative way:
```
const votesCount = Object.values(answers).map(optionAnswers => optionAnswers.length);
const maxVotes = Math.max(...votesCount) ?? 0;
const total = votesCount.reduce((a, b) => a + b, 0);
const winnerIndex = Object.entries(answers).find(([idx, votes]) => votes.length === maxVotes)?.[0] ?? -1;
```

2021-08-10 06:27 UTC, klesogor commented on slidez-fe-core/src/components/poll/Poll.scss
> +.poll {
since you're using scss you can do something like
```
.poll{
 &-header {}
 &-name {}
}
```

2021-08-10 06:29 UTC, klesogor commented on slidez-fe-core/src/components/poll/Poll.tsx
> +        prevCount = currCount
btw won't work, try
{
 0: 1
 1: 5
 2: 1
 3: 3
}

2021-08-10 06:30 UTC, klesogor requested changes
fix logic for winner index, optionally - rewrite declaratively

2021-08-13 09:20 UTC, klesogor approved these changes

2021-08-13 09:32 UTC, merged