add search function
BinaryStudioAcademy/bsa-2021-slidez pull request #57
Opened 2021-08-06 13:23 UTC by NDMyroshnychenko

Implement search client functionality

2021-08-06 17:11 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/dashboard/Dashboard.tsx
> +    // @ts-ignore
Don't use ts-ignore

2021-08-06 17:11 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/dashboard/Dashboard.tsx
> +    })
Please, use useEffect on searchField changes to filter presentations and store filtered presentations using useState()

2021-08-09 08:14 UTC, Anatolii-Ivanov requested changes

2021-08-09 08:14 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/dashboard/Dashboard.tsx
> +        )
You can use it without return statement
MOCK_DATA.filter((presentation) => presentation.name
                    .toLowerCase()
                    .includes(searchField.toLowerCase())
            )

2021-08-09 08:14 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/dashboard/Dashboard.tsx
> +    }
The same

2021-08-09 08:14 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/dashboard/Dashboard.tsx
> +                                {isNotEmptyPresentation()}
Can you add styles to it?)
like 
HTML:
```<div class="no-found-presentaitons"><p>Some text here</p></div>```

CSS:
.no-found-presenation {
display:flex;
justify-content: center;
align-content: center;
width: 100%;
height: 100%; // Here can be some troubles
font-weight: 400;
font-size: 16px;
}

2021-08-11 19:35 UTC, Anatolii-Ivanov approved these changes

2021-08-13 07:15 UTC, VladislavArzamastsev approved these changes

2021-08-13 07:16 UTC, merged