create participant page
BinaryStudioAcademy/bsa-2021-slidez pull request #97
Opened 2021-08-17 08:05 UTC by NDMyroshnychenko

**Create participant page**

- Mobile participant view page is created

- This page contains list of questions

- This page contains header with website logo

- Page route is like /event/{eventId}

- Endpoint for getting polls is created (mocked data) by this eventId

2021-08-17 10:54 UTC, Anatolii-Ivanov requested changes

2021-08-17 10:54 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/participant-page/header.scss
> +    background-color: #22313f;
Can you get color from global.scss file?

2021-08-17 10:54 UTC, Anatolii-Ivanov commented on slidez-fe-core/src/pages/participant-page/participantPage.scss
> +        color: #663999;
The same in this file

2021-08-19 06:57 UTC, Anatolii-Ivanov approved these changes

2021-08-19 09:07 UTC, AnnaPrusakova approved these changes

2021-08-19 10:53 UTC, merged